### PR TITLE
User feedback for subscriptions authorization

### PR DESCRIPTION
**Pull request by rsill-neo4j**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-203.surge.sh

Updated pages:
- [Subscriptions authorization](https://neo4j-docs-graphql-203.surge.sh/graphql/5/security/subscriptions-authorization)
- [Subscriptions](https://neo4j-docs-graphql-203.surge.sh/graphql/5/subscriptions)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-203.surge.sh

Updated pages:
- [Subscriptions authorization](https://neo4j-docs-graphql-203.surge.sh/graphql/5/security/subscriptions-authorization)
- [Subscriptions](https://neo4j-docs-graphql-203.surge.sh/graphql/5/subscriptions)

**Review by darrellwarde — APPROVED** [review]

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Comment by neo-technology-commit-status-publisher** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|6.x|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 203
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport) and see the [Github Action logs](https://github.com/neo4j/docs-graphql/actions/runs/11554850507) for details

**Comment by rsill-neo4j** [comment]
cherry-picked manually

**Pull request merged**
