### PR TITLE
Use secret instead of github_token

### PR DESCRIPTION
**Pull request by recrwplay**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Review by rsill-neo4j — APPROVED** [review]

**Comment by neo-technology-commit-status-publisher** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|6.x|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 209
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport) and see the [Github Action logs](https://github.com/neo4j/docs-graphql/actions/runs/11495635355) for details

**Comment by neo-technology-commit-status-publisher** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|6.x|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 209
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport) and see the [Github Action logs](https://github.com/neo4j/docs-graphql/actions/runs/11495635355) for details

**Comment by neo-technology-commit-status-publisher** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|6.x|[](https://github.com/neo4j/docs-graphql/pull/210)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport) and see the [Github Action logs](https://github.com/neo4j/docs-graphql/actions/runs/11495635355) for details

**Pull request merged**
