### PR TITLE
[typo] Update reference.adoc

### PR DESCRIPTION
**Pull request by mariusbutuc**
Fix typo _resolvers to_ » _resolves to_.

### CODE REVIEW

**Review by rsill-neo4j — APPROVED** [review]

**Comment by mariusbutuc** [comment]
Hey @rsill-neo4j, thank you kindly for looking into this!

I'm currently noticing this workflow feedback:
> 1 workflow awaiting approval
> This workflow requires approval from a maintainer.

As I'm new to contributing to this repo, would you happen to know if there are specific maintainers to ping as the next step, or does this tend to happen organically?

**Review by mariusbutuc — COMMENTED** [review]
Hey @rsill-neo4j, thank you kindly for looking into this!

I'm currently noticing this workflow feedback:
> 1 workflow awaiting approval
> This workflow requires approval from a maintainer.

As I'm new to contributing to this repo, would you happen to know if there are specific maintainers to ping as the next step, or does this tend to happen organically?

**Comment by rsill-neo4j** [comment]
> Hey @rsill-neo4j, thank you kindly for looking into this!
> 
> I'm currently noticing this workflow feedback:
> 
> > 1 workflow awaiting approval
> > This workflow requires approval from a maintainer.
> 
> As I'm new to contributing to this repo, would you happen to know if there are specific maintainers to ping as the next step, or does this tend to happen organically?

just triggered it. didn't notice before. thanks for the contribution :)

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Pull request merged**
