### PR TITLE
Left side navigation

### PR DESCRIPTION
**Pull request by rsill-neo4j**
Proposal for the left side navigation

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-137.surge.sh

Updated pages:
- [Driver configuration](https://neo4j-docs-graphql-137.surge.sh/graphql/5/driver-configuration)
- [Creating a new project](https://neo4j-docs-graphql-137.surge.sh/graphql/5/getting-started)
- [Aggregations](https://neo4j-docs-graphql-137.surge.sh/graphql/5/queries-aggregations/aggregations)
- [Queries and aggregations](https://neo4j-docs-graphql-137.surge.sh/graphql/5/queries-aggregations)
- [Queries](https://neo4j-docs-graphql-137.surge.sh/graphql/5/queries-aggregations/queries)
- [Schema configuration](https://neo4j-docs-graphql-137.surge.sh/graphql/5/schema-configuration)
- [Troubleshooting](https://neo4j-docs-graphql-137.surge.sh/graphql/5/troubleshooting)

**Review by lidiazuin — APPROVED** [review]
Great improvements in the content-nav! Thanks a lot Richard 😁

**Review by mjfwebb — APPROVED** [review]
I like these changes! Was there a particular motivation for putting "Authentication and Authorization" at the top of the reference section?

**Comment by rsill-neo4j** [comment]
> I like these changes! Was there a particular motivation for putting "Authentication and Authorization" at the top of the reference section?

Hm... probably because authentication is usually pretty high up in the navigation of similar product docs.
Should it go somewhere else?

**Comment by mjfwebb** [comment]
> > I like these changes! Was there a particular motivation for putting "Authentication and Authorization" at the top of the reference section?
> 
> Hm... probably because authentication is usually pretty high up in the navigation of similar product docs. Should it go somewhere else?

I don't know if it should go anywhere else, it might be well placed, as it is a popular feature of the library.

**Comment by neo-technology-commit-status-publisher** [comment]
Thanks for the documentation updates.

The preview documentation has now been torn down - reopening this PR will republish it.

**Pull request merged**
